# 川师大数据 {#bigdata}


```{r}
univ_discip_timeserial_2010_to_2019
```


```{r}
focus_discipline_cn <- c("工程学", "物理学", "数学", "化学", 
						 "材料科学", "计算机科学")

d <- univ_discip_timeserial_2010_to_2019 %>% 
	filter(	discipline_cn %in% focus_discipline_cn) 
d
```




## 全景对比

```{r}
# without gghighlight

highlight_school <- c("北京师范大学", "四川师范大学")

d1 <- d %>%
  group_by(univ_cn) %>%
  mutate(
    end_label = ifelse(year == max(year), univ_cn, NA_character_)
  ) %>%
  mutate(
    end_label = case_when(
      univ_cn %in% highlight_school ~ end_label,
      TRUE ~ NA_character_
    ),
    color_group = case_when(
      univ_cn %in% highlight_school ~ univ_cn,
      TRUE ~ "ZZOTHER"
    )
  ) %>%
  ungroup()
d1
```




```{r, fig.height = 8, fig.width = 6}
d1 %>% 
	mutate(univ_cn = factor(univ_cn) %>% 
		   	       fct_relevel("北京师范大学", "四川师范大学", after = Inf)
		   ) %>% 
	
  ggplot(aes(
    x = year, y = n_paper,
    color = color_group, label = end_label,
    group = univ_cn
  )) +
  geom_line(size = 0.8) +
  geom_point(data = . %>% filter(!is.na(end_label)),
  		   aes(fill = end_label),
  		   shape = 21, size = 2, 
  		   color = "white") +
  geom_text_repel(
    nudge_x = 1.1,
    nudge_y = 0.1,
    segment.color = NA
  ) +
  scale_color_manual(
  	values = c("北京师范大学" = "#195F90FF", 
  			   "四川师范大学" = "#D76500FF", 
  			    "ZZOTHER" = "gray80")
  	) +
  scale_fill_manual(
  	values = c("北京师范大学" = "#195F90FF", 
  			   "四川师范大学" = "#D76500FF", 
  			    "ZZOTHER" = "gray80")
  	) +
  guides(color = FALSE) +
  facet_wrap(vars(discipline_cn), scales = "free", ncol = 2) +
  #theme_minimal() +
  #myriad::theme_myriad(base_family = "wqy-microhei") +
  theme(legend.position = "none") +
  scale_x_continuous(breaks = c(seq(2000, 2019, by = 4), 2019) ) +
  labs(
    x = NULL, y = NULL,
    title = "历年发文情况"
  ) 
```







横向比较top30所师范类高校的学科发展情况

- 全景大图
高亮的（包括川师在内的四个学校）类似R4DS中的eda_covid2019
吸取[Kieran Healy大神的配色方案](https://github.com/kjhealy/covid) 

- 学科小图




## 进入百分之一的

https://www.hznu.edu.cn/c/2020-03-14/2338324.shtml
```{r}
univ_discip_enter_top_one_percent %>% 
	count(univ_cn) %>% 
	arrange(desc(n))

```

```{r}
univ_discip_enter_top_one_percent %>% 
	add_count(discipline_cn, name = "discip_occur_num") %>% 
	add_count(univ_cn, name = "univ_occur_num") %>% 
	mutate(univ_cn = glue::glue("{univ_cn}({univ_occur_num})")) 
```


```{r, fig.height = 6, fig.width = 8}
univ_discip_enter_top_one_percent %>% 
	add_count(discipline_cn, name = "discip_occur_num") %>% 
	add_count(univ_cn, name = "univ_occur_num") %>% 
	mutate(univ_cn = glue::glue("{univ_cn}({univ_occur_num})")) %>% 
	select(discipline_cn, univ_cn, top_papers, discip_occur_num, univ_occur_num) %>% 

	ggplot(aes(x = fct_reorder(discipline_cn, univ_occur_num, .desc = T), 
			   y = reorder(univ_cn, -1*discip_occur_num)) ) +
	geom_tile(color = "white", fill = "orange") +
	geom_text(aes(label = top_papers), size = 3) +
	theme_classic() +
	theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
	labs(x = NULL, y = NULL) +
   ggtitle("师范大学进入情况", subtitle = '（数据来源 ESI）') 
	
```




## one in percent
```{r}
focus_discipline <- c("工程学")

univ_discip_cum_last_ten_year %>% 
	filter(discipline_cn %in% focus_discipline) %>% 
	arrange(-cum_cited)

```

```{r}
focus_discipline <- c("工程学")
label_school <- c("四川师范大学", "北京师范大学", "南京师范大学", 
				  "杭州师范大学", "华南师范大学", "陕西师范大学")

univ_discip_cum_last_ten_year %>% 
	filter(discipline_cn %in% focus_discipline) %>% 
	mutate(
    label = ifelse(univ_cn %in% label_school, univ_cn, "")
  ) %>%
	
  ggplot(aes(x = cum_paper, y = cum_cited, fill = is_enter_one_percent)) +
  geom_point(
    size = 3.5,
    alpha = .9,
    shape = 21,
    col = "white"#,
    #fill = "#0162B2"
  ) +
  geom_text_repel(
    aes(label = label),
    size = 4.5,
    point.padding = .2,
    box.padding = .3,
    force = 1,
    min.segment.length = 0
  ) +
 geom_hline(aes(yintercept = Threshold0326)) +
 annotate("text", x = 1250, y = 3200, 
			 label = "进入双一流学科的阈值线", size = 4, color = "red") +
  theme_minimal(14) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank()
  ) +
  labs(
  	title = "师范类院校工程学科进入前1%ESI学科",
	subtitle = "ESI数据库2020年03月26日数据",
    x = "累积发文量(2010-2020)",
    y = "累积引文量(2010-2020)"
  )
	
```

发文量超过杭州师大 ，但引文差一点点







## 化学
```{r}
focus_discipline <- c("化学")
label_school <- c("四川师范大学", "北京师范大学", "南京师范大学", 
				  "杭州师范大学", "华南师范大学", "陕西师范大学")

univ_discip_cum_last_ten_year %>% 
	filter(discipline_cn %in% focus_discipline) %>% 
	mutate(
    label = ifelse(univ_cn %in% label_school, univ_cn, "")
  ) %>%
	
	
  ggplot(aes(x = cum_paper, y = cum_cited, fill = is_enter_one_percent)) +
  geom_point(
    size = 3.5,
    alpha = .9,
    shape = 21,
    col = "white"#,
    #fill = "#0162B2"
  ) +
  geom_text_repel(
    aes(label = label),
    size = 4.5,
    point.padding = .2,
    box.padding = .3,
    force = 1,
    min.segment.length = 0
  ) +
 geom_hline(aes(yintercept = Threshold0326)) +
 annotate("text", x = 3500, y = 12000, 
			 label = "进入双一流学科的阈值线", size = 4, color = "red") +
  theme_minimal(14) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank()
  ) +
  labs(
  	title = "师范类院校化学学科进入前1%ESI学科",
	subtitle = "ESI数据库2020年03月26日数据",
    x = "累积发文量(2010-2020)",
    y = "累积引文量(2010-2020)"
  )
	
```

## 物理
```{r}
focus_discipline <- c("物理学")
label_school <- c("四川师范大学", "北京师范大学", "南京师范大学", 
				  "杭州师范大学", "华南师范大学", "陕西师范大学")

univ_discip_cum_last_ten_year %>% 
	filter(discipline_cn %in% focus_discipline) %>% 
	mutate(
    label = ifelse(univ_cn %in% label_school, univ_cn, "")
  ) %>%
	
	
  ggplot(aes(x = cum_paper, y = cum_cited, fill = is_enter_one_percent)) +
  geom_point(
    size = 3.5,
    alpha = .9,
    shape = 21,
    col = "white"#,
    #fill = "#0162B2"
  ) +
  geom_text_repel(
    aes(label = label),
    size = 4.5,
    point.padding = .2,
    box.padding = .3,
    force = 1,
    min.segment.length = 0
  ) +
 geom_hline(aes(yintercept = Threshold0326)) +
 annotate("text", x = 500, y = 23000, 
			 label = "进入双一流学科的阈值线", size = 4, color = "red") +
  theme_minimal(14) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank()
  ) +
  labs(
  	title = "师范类院校物理学科进入前1%ESI学科",
	subtitle = "ESI数据库2020年03月26日数据",
    x = "累积发文量(2010-2020)",
    y = "累积引文量(2010-2020)"
  )
	
```

## 数学
```{r}
focus_discipline <- c("数学")
label_school <- c("四川师范大学", "北京师范大学", "南京师范大学", 
				  "杭州师范大学", "华南师范大学", "陕西师范大学")

univ_discip_cum_last_ten_year %>% 
	filter(discipline_cn %in% focus_discipline) %>% 
	mutate(
    label = ifelse(univ_cn %in% label_school, univ_cn, "")
  ) %>%
	
	
  ggplot(aes(x = cum_paper, y = cum_cited, fill = is_enter_one_percent)) +
  geom_point(
    size = 3.5,
    alpha = .9,
    shape = 21,
    col = "white"#,
    #fill = "#0162B2"
  ) +
  geom_text_repel(
    aes(label = label),
    size = 4.5,
    point.padding = .2,
    box.padding = .3,
    force = 1,
    min.segment.length = 0
  ) +
 geom_hline(aes(yintercept = Threshold0326)) +
 annotate("text", x = 300, y = 5300, 
			 label = "进入双一流学科的阈值线", size = 4, color = "red") +
  theme_minimal(14) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank()
  ) +
  labs(
  	title = "师范类院校数学学科进入前1%ESI学科",
	subtitle = "ESI数据库2020年03月26日数据",
    x = "累积发文量(2010-2020)",
    y = "累积引文量(2010-2020)"
  )
	
```
## 学科对比

分面各校，高亮川师  

现在我们可以试试 **bookdown** 的一些初级功能了，例如图表。图 \@ref(fig:hello) 是一幅无趣的散点图，表 \@ref(tab:iris) 是一份枯燥的数据。

```{r hello, fig.cap='雷猴啊，散点图！', out.width='90%'}
par(mar = c(4, 4, 1, .1))
plot(cars, pch = 19)
```

```{r iris}
knitr::kable(
  head(iris), caption = '雷猴啊，iris 数据！',
  booktabs = TRUE
)
```

就这样，你可以一直编下去，直到编不下去。