# 学科预测 {#predict}
 
本章的主要工作是，计算并预测川师未来三年进入双一流学科的概率。
可能一点意义也没有

```{r}
univ_discip_cum_last_ten_year %>% 
  filter(univ_cn == "四川师范大学") %>% 
  select(univ_cn, discipline_cn, cum_cited, Threshold0326) %>% 
  mutate(prop = cum_cited/Threshold0326) %>% 
  arrange(desc(prop)) %>% 
  mutate(prop = scales::percent(prop, accuracy = 0.01))
```


## 统计方法
- 贝叶斯数据分析
- 模型不好怎么办？
- log10 scale


关于模型，学科的发展和很多方面都有关系，因此建立一个完全正确的模型是不可能的。正如英国统计学家George E. P. Box所说，所有模型都是错的，但其中有些是有用的。
所以与其去建立复杂的模型，并给解释带来更多困扰，不如就从最简单的出发。

```{r}
focus <- c("计算机科学", "工程学", "化学", "材料科学")

d <- univ_discip_timeserial_2000_to_2019 %>% 
	filter(univ_cn == "四川师范大学") %>% 
	filter(discipline_cn %in% focus) %>% 
	select(discipline_cn, year, n_paper, n_cited) %>% 
	complete(discipline_cn, year) 
	
d
```


```{r}
d %>% 
	ggplot(aes(x = year, y = n_cited)) +
	geom_point() +
	geom_smooth(method = lm, se = FALSE) +
	facet_wrap(vars(discipline_cn), scales = "free_y")
	
	
```

## 工程学
```{r}
d_eng <- d %>%  
	filter(discipline_cn %in% "工程学") %>% 
	filter(between(year, 2000, 2019)) 
d_eng
```

弥补2012-2013年期间的短板有所下滑，从而导致

```{r}
d_eng_cum <- d_eng %>% 
    mutate(
	cum_cited = slider::slide_dbl(n_cited, sum, na.rm = TRUE, .before = 9, .step = 1, .complete = TRUE)
) %>% 
	filter(between(year, 2009, 2019))

d_eng_cum
```



```{r}
d_eng %>% 
	ggplot(aes(x = year, y = n_cited)) +
	geom_point() +
	geom_smooth(method = lm, se = FALSE)

d_eng_cum %>% 
	ggplot(aes(x = year, y = cum_cited)) +
	geom_point() +
	geom_smooth(method = lm, se = FALSE)
```

```{r}
brms_eng <- brms::brm(
    data = d_eng,
    family = gaussian,
    n_cited | trunc(lb = 0) ~ 1 + year,
    set_prior("normal(22, 10)", lb = 0, class = "b"),
    #prior = c(
     # prior(normal(20, 100),  class = Intercept),
    #  prior(normal(22, 100), class = b)
    #  prior(uniform(0, 50), class = sigma)
   # ),
    iter = 4000, warmup = 2000, chains = 4, cores = 4,
    seed = 1024,
    control = list(adapt_delta = 0.99, 
                   max_treedepth = 13),
    file = "fits/b_eng"
  )
```


```{r}
brms_eng
```


```{r}
plot(brms_eng)
```
```{r}
brms_eng %>% posterior_summary()
```

```{r}
pp_check(brms_eng)
```



```{r}
tb <- tibble(
	year = c(2020)
)

# 需要2011-2019九年的累积量
exist_nine_year_cum_cited <- d_eng %>% 
	filter(between(year, 2011, 2019)) %>% 
	summarise(
		exist_cum_cited = sum(n_cited)
	) %>% 
	pull()

exist_nine_year_cum_cited
```


```{r}
post_draw <- tb %>% add_predicted_draws(brms_eng)
post_draw
```
```{r}
post_draw %>% 
	ggplot(aes(x = .prediction, y = year)) +
    stat_halfeyeh()
```



```{r}
post_draw <- post_draw %>% 
	mutate(
	.prediction = .prediction +  exist_nine_year_cum_cited
)
post_draw
```

```{r}
post_draw %>% tidybayes::mode_hdi()
post_draw %>% tidybayes::mean_qi()
```


```{r}
prob_pred <- post_draw %>% 
	group_by(year) %>% 
	summarise(
		pred_mean = mean(.prediction),
		prob_above_line = mean(.prediction >= 2843)
	)
prob_pred
```

```{r}
post_draw %>% 
	ggplot(aes(x = .prediction, y = factor(year), fill = stat(x > 2843))) +
	stat_halfeyeh() +
	geom_vline(xintercept = 2843, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue"))
```


```{r}
post_draw %>% 
	ggplot(
		aes(x = year, y = .prediction, fill = stat(y > 2843)) 
	) +
	stat_eye(side = "right") +
	geom_point(data = d_eng_cum, aes(x = year, y = cum_cited)) +
	geom_hline(yintercept = 2843, linetype = "dashed", size = 1,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue")) +
	annotate("text", x = 2012, y = 3000, 
			 label = "进入双一流学科的阈值线", size = 4, color = "red") +
	scale_x_continuous(breaks = c(seq(2009, 2019, by = 2), 2020),
					   labels = c(seq(2009, 2019, by = 2), 2020)
					   )
```



```{r, fig.asp = 0.618}
# plot original data and predict data together
library(ggforce)
desc <- "高于阈值线的概率"


post_draw %>% 
	ggplot(
	  aes(x = year, y = .prediction, fill = stat(y > 2843)) 
	) +
  stat_eye(side = "right") +
  geom_point(data = d_eng_cum, aes(x = year, y = cum_cited)) +
  geom_hline(
    yintercept = 2843, linetype = "dashed", size = 1,
    color = "red"
  ) +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  annotate("text",
    x = 2012, y = 2975,
    label = "进入ESI前1%学科的阈值线(2020-03-26数据)", size = 4, color = "red"
  ) +
  geom_mark_ellipse(aes(
    x = 2020, y = 3200,
    label = "贝叶斯预测", description = desc
  ),
  # label.family = "Space Mono",
   label.fontsize = 11,
   label.colour = c("#CC79A7", "black"),
   label.fill = NA,
   label.buffer = unit(0.1, "mm"), # 标签与指定xy点的间距
   colour = NA,
   fill = NA
  ) +
  geom_text(data = prob_pred, aes(
    x = year + 0.5,
    y = pred_mean,
    label = scales::percent(prob_above_line, accuracy = 0.1)
  )) +
  scale_y_continuous(
  	limits = c(600,NA),
  	expand = expansion(mult = c(0, NA))
  	) +
 scale_x_continuous(
 	breaks = c(seq(2009, 2020, by = 1)),
	labels = c(seq(2009, 2020, by = 1)),
 	expand = expansion(mult = c(0.05, 0.1))
 ) + 
  theme_classic() +
  theme(legend.position = "none",
  	  #axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
  	  ) +
  labs(
    title = "工程学科未来一年进入ESI前1%学科的概率",
    subtitle = "基于引文量的贝叶斯预测",
    x = "时间（年）",
    y = "前十年累积引文量"
  )
```




## 化学
```{r}
d_chem <- d %>%  
	filter(discipline_cn %in% "化学") %>% 
	filter(between(year, 2000, 2019)) 
d_chem
```



```{r}
d_chem_cum <- d_chem %>% 
    mutate(
	cum_cited = slider::slide_dbl(n_cited, sum, na.rm = TRUE, .before = 9, .step = 1, .complete = TRUE)
) %>% 
	filter(between(year, 2009, 2019))

d_chem_cum
```



```{r}
d_chem %>% 
	ggplot(aes(x = year, y = n_cited)) +
	geom_point() +
	geom_smooth(method = lm, se = FALSE)

d_chem_cum %>% 
	ggplot(aes(x = year, y = cum_cited)) +
	geom_point() +
	geom_smooth(method = lm, se = FALSE)
```

```{r}
brms_chem <- brms::brm(
    data = d_chem,
    family = gaussian,
    n_cited | trunc(lb = 0) ~ 1 + year,
    #prior = c(
    #  prior(normal(178, 100), class = Intercept),
    #  prior(normal(2.5, 10), class = b),
    #  prior(uniform(0, 50), class = sigma)
    #),
    iter = 4000, warmup = 2000, chains = 4, cores = 4,
    seed = 1024,
    control = list(adapt_delta = 0.99, 
                 max_treedepth = 13),
    file = "fits/b_chem"
  )
```


```{r}
brms_chem
```


```{r}
plot(brms_chem)
```
```{r}
brms_chem %>% posterior_summary()
```

```{r}
pp_check(brms_chem)
```

```{r}
tb <- tibble(
	year = c(2020)
)

# 需要2011-2019九年的累积量
exist_nine_year_cum_cited <- d_chem %>% 
	filter(between(year, 2011, 2019)) %>% 
	summarise(
		exist_cum_cited = sum(n_cited)
	) %>% 
	pull()

exist_nine_year_cum_cited
```


```{r}
post_draw <- tb %>% add_predicted_draws(brms_chem)
post_draw
```
```{r}
post_draw %>% 
	ggplot(aes(x = .prediction, y = year)) +
    stat_halfeyeh()
```

```{r}
post_draw <- post_draw %>% 
	mutate(
	.prediction = .prediction +  exist_nine_year_cum_cited
)
post_draw
```



```{r}
prob_pred <- post_draw %>% 
	group_by(year) %>% 
	summarise(
		pred_mean = mean(.prediction),
		prob_above_line = mean(.prediction >= 8502)
	)
prob_pred
```


8502-4697 还差3805，预测1000
即使三月份累积了5545，但2010年848是一大托


```{r, fig.asp = 0.618}
# plot original data and predict data together
library(ggforce)
desc <- "高于阈值线的概率"


post_draw %>% 
	ggplot(
	  aes(x = year, y = .prediction, fill = stat(y > 8502)) 
	) +
  stat_eye(side = "right") +
  geom_point(data = d_chem_cum, aes(x = year, y = cum_cited)) +
  geom_hline(
    yintercept = 8502, linetype = "dashed", size = 1,
    color = "red"
  ) +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  annotate("text",
    x = 2013, y = 8200,
    label = "进入ESI前1%学科的阈值线(2020-03-26数据)", size = 4, color = "red"
  ) +
  geom_mark_ellipse(aes(
    x = 2020, y = 6000,
    label = "贝叶斯预测", description = desc
  ),
  # label.family = "Space Mono",
   label.fontsize = 11,
   label.colour = c("#CC79A7", "black"),
   label.fill = NA,
   label.buffer = unit(0.1, "mm"), # 标签与指定xy点的间距
   colour = NA,
   fill = NA
  ) +
  geom_text(data = prob_pred, aes(
    x = year + 0.5,
    y = pred_mean,
    label = scales::percent(prob_above_line)
  )) +
  scale_y_continuous(
  	limits = c(1800,10000),
  	expand = expansion(mult = c(0, NA))
  	) +
 scale_x_continuous(
 	breaks = c(seq(2009, 2020, by = 1)),
	labels = c(seq(2009, 2020, by = 1)),
 	expand = expansion(mult = c(0.05, 0.1))
 ) + 
  theme_classic() +
  theme(legend.position = "none",
  	  #axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
  	  ) +
  labs(
    title = "化学学科未来一年进入ESI前1%学科的概率",
    subtitle = "基于引文量的贝叶斯预测",
    x = "时间（年）",
    y = "前十年累积引文量"
  )
```





## 数学学科

## 物理学科

### 数据


### 先验概率
```{r, eval = FALSE}
ggplot(
  data = d2,
  aes(x = weight, y = height)
) +
  geom_point(shape = 1, size = 2) +
  theme_bw() +
  theme(panel.grid = element_blank())



# prior for mu $\text{Normal}(178, 100)$
ggplot(
  data = tibble(x = seq(from = 100, to = 250, by = .1)),
  aes(x = x, y = dnorm(x, mean = 178, sd = 20))
) +
  geom_line() +
  ylab("density")


# prior for beta $\text{Normal}(0, 10)$
tibble(beta = -40:40) %>%
  mutate(density = dnorm(beta, mean = 0, sd = 10)) %>%
  ggplot(aes(x = beta, ymin = 0, ymax = density)) +
  geom_ribbon(size = 0, fill = "royalblue") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(expression(beta)) +
  theme(panel.grid = element_blank())

# prior for sigma $\text{Uniform}(0, 50)$
tibble(x = seq(from = -10, to = 60, by = .1)) %>%

  ggplot(aes(x = x, y = dunif(x, min = 0, max = 50))) +
  geom_line() +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())
```






## 化学学科
## 工程学科

## 计算机学科

具体参考 <https://mc-stan.org/docs/2_22/stan-users-guide/prediction-forecasting-and-backcasting.html>

```{r}
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = "-march=native")




# put into a list
stan_dat <- list(
	N = nrow(d2),
	x = d2$year,
	y = d2$n_cited,
	M = nrow(tb),
	new_x = tb$year
)




fit <- stan(file = "./models/simple.stan", 
			data = stan_dat,
			iter = 41000, 
			chains = 4, 
			warmup = 40000, 
			control = list(adapt_delta = 0.99, 
                           max_treedepth = 13),
			cores = 4)
```




```{r}
fit
```





```{r, eval=FALSE}
plot(fit, pars = c("alpha", "beta"))
```


```{r, eval=FALSE}
stan_trace(fit)
```


```{r, eval=FALSE}
stan_plot(fit, pars = c("alpha", "beta"))
```


```{r, eval=FALSE}
stan_hist(fit, pars = c("alpha", "beta"))
```


```{r, eval=FALSE}
stan_dens(fit, pars = c("alpha", "beta"))
```


```{r, eval=FALSE}
get_posterior_mean(fit)
as.data.frame(fit) %>% as_tibble()
```


```{r, eval=FALSE}
fit %>% tidybayes::spread_draws(alpha, beta)

fit %>% tidybayes::spread_draws(new_y[n]) 
fit %>% tidybayes::spread_draws(new_y[weight]) 
fit %>% tidybayes::spread_draws(new_y[condition]) 

fit %>% tidybayes::spread_draws(new_y[i]) %>% 
	median_qi()
```


```{r, eval=FALSE}
fit %>%
	spread_draws(beta) %>%
	ggplot(aes(y = 0, x = beta, fill = stat(x > 1.5))) +
	stat_halfeyeh() +
	geom_vline(xintercept = 1.5, linetype = "dashed") +
	scale_fill_manual(values = c("gray80", "skyblue"))
```

### 预测
```{r}
library(tidybayes)

# stanfit模型不能用add_predicted_draws(fit)， 很遗憾
# 只有先写在.stan文件里， 预测写在generated quantities里

post_draw1 <- fit %>% tidybayes::spread_draws(new_y[condition]) 
post_draw1
```


```{r}
post_draw2 <- post_draw1 %>% 
	ungroup() %>% 
	mutate(
	year = case_when(
		condition == 1 ~  2020,
		condition == 2 ~  2021,
		condition == 3 ~  2022,
		TRUE ~ NA_real_
	)
)
post_draw2
```

```{r}
prob_pred1 <- post_draw2 %>% 
	group_by(year) %>% 
	summarise(
		pred_mean = mean(new_y),
		prob_above_line = mean(new_y >= 3040)
	)
prob_pred1
```


```{r}
post_draw2 %>% 
	ggplot(aes(x = new_y, y = factor(year), fill = stat(x > 3040))) +
	stat_halfeyeh() +
	geom_vline(xintercept = 3040, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue")) 
```



```{r}
post_draw2 %>% 
	ggplot(
		aes(x = factor(year), y = new_y, fill = stat(y > 3040)) 
	) +
	stat_eye(side = "right") +
	geom_hline(yintercept = 3040, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue"))
```




```{r, fig.asp = 0.816}
# plot original data and predict data together
library(ggforce)
desc <- "未来三年进入双一流学科的概率"


post_draw2 %>% 
	ggplot(
		aes(x = year, y = new_y, fill = stat(y > 3040)) 
	) +
  stat_eye(side = "right") +
  geom_point(data = d2, aes(x = year, y = n_cited)) +
  geom_hline(
    yintercept = 3040, linetype = "dashed", size = 1,
    color = "red"
  ) +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  annotate("text",
    x = 2004, y = 3040 + 3,
    label = "进入双一流学科的阈值线", size = 4, color = "red"
  ) +
  geom_mark_ellipse(aes(
    x = 2020, y = 3060,
    label = "贝叶斯预测", description = desc
  ),
  # label.family = "Space Mono",
   label.fontsize = 11,
   label.colour = c("#CC79A7", "black"),
   label.fill = NA,
   label.buffer = unit(0.1, "mm"), # 标签与指定xy点的间距
   colour = NA,
   fill = NA
  ) +
  geom_text(data = prob_pred1, aes(
    x = year,
    y = pred_mean,
    label = scales::percent(prob_above_line)
  )) +
  scale_y_continuous(
  	expand = expansion(mult = c(0, NA))
  	) +
 scale_x_continuous(
 	breaks = c(2000:2022),
 	labels = c(2000:2022),
 	expand = expansion(mult = c(0.05, 0.1))
 ) + 
  theme_classic() +
  theme(legend.position = "none",
  	  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
  	  ) +
  labs(
    title = "物理学科未来三年进入双一流学科的概率",
    subtitle = "基于引文量的贝叶斯预测",
    x = "时间（年）",
    y = "被引量"
  )

```

## 其他学科
如果需要了解其他学科的信息，请联系本文作者^[38552109@qq.com]
