--- 
title: "大数据背景下精准科研信息服务"
subtitle: "2020年版"
author: 
  - 王敏杰
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: elegantbook
bibliography: [book.bib]
biblio-style: apalike
logo: "figure/logo.png"
cover: "figure/cover.jpg"
#institute: "Elegant LaTeX Program"
extrainfo: "Victory won't come to us unless we go to it. --- M. Moore"
version: "0.1"
github-repo: perlatex/ElegantBookdown4IS
classoption: "cn, 11pt, fancy, hide"
#indent: 40pt
#subparagraph: yes
description: "This is a bookdown template based on ElegantBook. The output format for this template is bookdown::gitbook and bookdown::pdf_book."
---

\mainmatter

\hypersetup{pageanchor=true}


```{r setup, include=FALSE}
set.seed(1024)

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  out.width = "100%",
  fig.align = "center",
  fig.pos = "H",
  #fig.asp = 0.618, # 1 / phi
  fig.show = "hold",
  fig.showtext = TRUE
)
```

# 前言 {-}

```{r}
library(tidyverse)
library(tidybayes)
library(patchwork)
library(gghighlight)
library(ggrepel)
library(ggforce)
library(rstan)
library(brms)
library(scales)
library(here)
library(fs)
library(broom)
library(bookdown)
library(knitr)
library(kableExtra)
library(showtext)
showtext_auto()
```



```{r}
source("./scripts/01_read_raw_data.R")
source("./scripts/02_read_thresholdESI.R")
source("./scripts/theme_mystyle.R")
```

时隔5年，重新做评价，兼顾客观性、科学性和建设性，不是一件容易的事情

## 进度表 {-}

- 文献调研（3月底完成）
- 数据获取（4月中旬完成）
- 数学分析和模型评估（5月中旬完成）
- 可视化（6月初完成）
- 报告初稿（6月底完成）
- 研讨会（待定）
- 正式稿发布（7月初）



## 关于本文档 {-}

本报告使用R和stan语言完成，数据和代码存放在GitHub仓库<https://github.com/perlatex/ElegantBookdown4IS>，欢迎批评指正。

## 感谢 {-}

感谢彭凤老师在图书购买上提供的帮助，感谢同学协助完成数据收集和整理工作，感谢黄湘云老师帮忙检查了Stan代码。

